In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
from building_models.numerical_representation.encoders import EncodeSequences
from building_models.utils.utils_functions import UtilsFunctions

In [3]:
path_data = "../../processed_dataset/"

In [4]:
df_data = pd.read_csv(f"{path_data}processed_data/processed_dataset.csv")
df_data = df_data[["sequence", "label", "id"]]
df_data.head(5)

                                            sequence  label     id
0  EKKSINECDLKGKKVLIRVDFNVPVKNGKITNDYRIRSALPTLKKV...      1  seq_1
1  GHMARTVNLKGNPVTLVGPELKVGDRAPEAVVVTKDLQEKIVGGAK...      1  seq_2
2  GHMEERVLGMPAVESNMFPLGKQAPPFALTNVIDGNVVRLEDVKSD...      1  seq_3
3  GHMVEIGELAPDFELPDTELKKVKLSALKGKVVVLAFYPAAFTQVC...      1  seq_4
4  GSSGSSGTEERLKEIEAKYDEIAKDWPKKVKHVLHEEHELELTRVQ...      1  seq_5

In [5]:
df_errors = pd.read_csv(f"{path_data}processed_data/sequences_with_errors.csv")
df_errors = df_errors[["sequence"]]
df_errors.head(5)

                                            sequence
0  MAGQKIRIRLKAYDHEAIDASARKIVETVVRTGASVVGPVPLPTEK...
1  MAHKKAGGSTRNGRDSESKRLGVKRFGGESVLAGNIIVRQRGTKFH...
2  MAIDENKQKALAAALGQIEKQFGKGSIMRLGEDRSMDVETISTGSL...
3  MAKISKRRQAFAAKVDRQKLYAIEDALSLVKECASAKFDESIDVAV...
4  MARDIAAPPVPTNHQELISWVNEIAELTQPDAVVWCDGSEAEYERL...

In [6]:
df_unlabeled = pd.read_csv(f"{path_data}processed_data/unlabeled_data.csv")
df_unlabeled = df_unlabeled[["sequence"]]
df_unlabeled.head(5)

                                            sequence
0  MAAAAGRLLWSSVARHASAISRSISASTVLRPVASRRTCLTDILWS...
1  MAAAVGRLLRASVARHVSAIPWGISATAALRPAACGRTSLTNLLCS...
2  MAAKTGSQLERSISTIINVFHQYSRKYGHPDTLNKAEFKEMVNKDL...
3  MAALDAIREALPEPARDIKLNLQAVLQPGPLTPAQRWGVAVATAAA...
4  MAALKAGRGANWSLRAWRALGGIFWRKPPLLAPDLRALLTSGTPDS...

- Getting baseline representation

In [7]:
UtilsFunctions.make_directory(f"{path_data}encoded_data/one_hot")

In [8]:
for data in [(df_data, "full_data"), (df_errors, "error_data"), (df_unlabeled, "unlabeled_data")]:
    dataset = data[0]
    name_export = data[1]

    df_one_hot = EncodeSequences.encode_dataset(df=dataset, column_with_sequence="sequence", method="one_hot")
    df_one_hot = df_one_hot.merge(right=df_data, on="sequence")
    df_one_hot = df_one_hot.drop(columns=["is_canon"])
    df_one_hot.to_csv(f"{path_data}encoded_data/one_hot/{name_export}.csv", index=False)

In [9]:
UtilsFunctions.make_directory(f"{path_data}encoded_data/esm2_t6_8M_UR50D")

In [10]:
for data in [(df_data, "full_data"), (df_errors, "error_data"), (df_unlabeled, "unlabeled_data")]:
    dataset = data[0]
    name_export = data[1]

    df_embedding = EncodeSequences.get_embeddings(df=dataset, column_with_sequence="sequence")
    df_embedding = df_embedding.merge(right=df_data, on="sequence")
    df_embedding = df_embedding.drop(columns=["is_canon"])
    df_embedding.to_csv(f"{path_data}encoded_data/esm2_t6_8M_UR50D/{name_export}.csv", index=False)

Some weights of EsmModel were not initialized from the model checkpoint at /scratch/global_1/dmedina/sylphy/models/huggingface/facebook/esm2_t6_8M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of EsmModel were not initialized from the model checkpoint at /scratch/global_1/dmedina/sylphy/models/huggingface/facebook/esm2_t6_8M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of EsmModel were not initialized from the model checkpoint at /scratch/global_1/dmedina/sylphy/models/huggingface/facebook/esm2_t6_8M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.