In [1]:
import pandas as pd

In [2]:
path_data = "../../processed_dataset/"
path_export = "../../pipelines/data/"

In [3]:
df_data_filtered = pd.read_csv(f"{path_data}processed_data/processed_dataset.csv")

In [4]:
df_data_filtered.head()

,sequence,AMPDB v1,ANOX,AOD,AOPxSVM,Ahmad et al,Butt et al,Feng et al,Lam et al,PredAoDP,...,Zhang et al,count_0,count_1,n_valid_sources,count_0_norm,count_1_norm,label,length,is_canon,is_in_length
0,AEEPKMRALGAVVALLLCGQLFAAETGNEATDATDDSCPKPPEIPK...,1,999,999,999,999,999,999,999,999,...,999,0,1,1,0.0,1.0,1,352,True,True
1,AEWSCAKPAEIEHGYVEHLIRYRCDPHYRLRGSSDGEARGAGTAPR...,1,999,999,999,999,999,999,999,999,...,999,0,1,1,0.0,1.0,1,339,True,True
2,AKEKGGKLTAGLAAGGHWNPNKAPHHGFPWSDDAHLGDLPALTVLH...,999,999,1,999,999,999,999,999,999,...,999,0,1,1,0.0,1.0,1,86,True,True
3,ALGALVTLLLWGQLFAMDINNEVTEIADDSCPKPPEIANGYVEHLV...,1,999,999,999,999,999,999,999,999,...,999,0,1,1,0.0,1.0,1,345,True,True
4,ALGAVIALLLWGQLFAVDSGNDVMDISDDGCPKPPQIAHGYVEHSV...,1,999,999,999,999,999,999,999,999,...,999,0,1,1,0.0,1.0,1,305,True,True

In [5]:
df_data_filtered = df_data_filtered[["sequence", "label"]]
df_data_filtered["id"] = [f"seq_{i+1}" for i in range(df_data_filtered.shape[0])]

In [6]:
df_data_filtered.head()

                                            sequence  label     id
0  AEEPKMRALGAVVALLLCGQLFAAETGNEATDATDDSCPKPPEIPK...      1  seq_1
1  AEWSCAKPAEIEHGYVEHLIRYRCDPHYRLRGSSDGEARGAGTAPR...      1  seq_2
2  AKEKGGKLTAGLAAGGHWNPNKAPHHGFPWSDDAHLGDLPALTVLH...      1  seq_3
3  ALGALVTLLLWGQLFAMDINNEVTEIADDSCPKPPEIANGYVEHLV...      1  seq_4
4  ALGAVIALLLWGQLFAVDSGNDVMDISDDGCPKPPQIAHGYVEHSV...      1  seq_5

In [7]:
df_data_filtered.to_csv(f"{path_export}/sequences.csv", index=False)