In [6]:
import pandas as pd
from sylphy.embedding_extractor import create_embedding
from sklearn.preprocessing import normalize

In [3]:
df_data = pd.read_csv("../pipelines/data/sequences.csv")
df_data.head()

                                            sequence  label     id
0  AEEPKMRALGAVVALLLCGQLFAAETGNEATDATDDSCPKPPEIPK...      1  seq_1
1  AEWSCAKPAEIEHGYVEHLIRYRCDPHYRLRGSSDGEARGAGTAPR...      1  seq_2
2  AKEKGGKLTAGLAAGGHWNPNKAPHHGFPWSDDAHLGDLPALTVLH...      1  seq_3
3  ALGALVTLLLWGQLFAMDINNEVTEIADDSCPKPPEIANGYVEHLV...      1  seq_4
4  ALGAVIALLLWGQLFAVDSGNDVMDISDDGCPKPPQIAHGYVEHSV...      1  seq_5

In [4]:
embedder = create_embedding(
    model_name="facebook/esm2_t6_8M_UR50D",
    dataset=df_data,
    column_seq="sequence",
    name_device="cuda",
    precision="fp32"
)

In [5]:
embedder.run_process(batch_size=16, pool="mean")

Some weights of EsmModel were not initialized from the model checkpoint at /home/david/.cache/sylphy/models/huggingface/facebook/esm2_t6_8M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [7]:
df_encoders = embedder.coded_dataset
df_encoders

,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,...,p_311,p_312,p_313,p_314,p_315,p_316,p_317,p_318,p_319,sequence
0,-0.014591,-0.192701,0.352768,0.105751,0.119550,-0.285546,-0.133910,0.112170,-0.171077,-0.139355,...,-0.013255,-0.009908,0.199713,-0.122715,-0.236230,-0.023601,0.173426,0.085588,-0.083000,AEEPKMRALGAVVALLLCGQLFAAETGNEATDATDDSCPKPPEIPK...
1,0.033251,-0.256825,0.338001,0.101427,0.139848,-0.355665,-0.151309,0.140057,-0.244258,-0.108110,...,-0.072434,0.006621,0.182074,-0.190825,-0.150008,0.032611,0.204408,0.187569,-0.178067,AEWSCAKPAEIEHGYVEHLIRYRCDPHYRLRGSSDGEARGAGTAPR...
2,-0.099718,-0.104878,0.146885,0.044325,0.126373,-0.030270,-0.002684,-0.102963,-0.107109,-0.167737,...,0.039405,0.004715,-0.031855,0.135585,-0.133456,-0.113744,0.260476,0.040607,-0.065694,AKEKGGKLTAGLAAGGHWNPNKAPHHGFPWSDDAHLGDLPALTVLH...
3,0.050603,-0.213978,0.402723,0.072415,0.113552,-0.359710,-0.150402,0.164758,-0.111409,-0.135381,...,-0.058305,0.040180,0.191711,-0.117037,-0.225503,-0.014409,0.143456,0.081892,-0.135656,ALGALVTLLLWGQLFAMDINNEVTEIADDSCPKPPEIANGYVEHLV...
4,0.001075,-0.186747,0.357364,0.080738,0.101011,-0.376996,-0.129640,0.124668,-0.164286,-0.135388,...,-0.060997,0.012968,0.212838,-0.144146,-0.256838,-0.020279,0.146324,0.119670,-0.110290,ALGAVIALLLWGQLFAVDSGNDVMDISDDGCPKPPQIAHGYVEHSV...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4188,-0.026423,-0.023233,0.161979,0.040162,0.094322,0.016583,-0.056209,-0.101300,-0.028606,-0.075539,...,0.080804,-0.034752,0.105899,0.093961,-0.208047,-0.113496,0.162105,0.090851,-0.021752,YFQGMLKNIDPALNADVLHALRAMGHGDTLVISDTNFPSDSVARQT...
4189,-0.112805,-0.091957,-0.056899,-0.002581,0.182168,-0.038435,0.117173,-0.050015,-0.176281,-0.092321,...,0.019004,0.012523,0.017389,-0.113801,-0.103579,-0.099447,0.267243,-0.066038,0.012162,YPMNINDALTSILASKKYRALCPDTVRRILTEEWGRHKSPKQTVEA...
4190,-0.036029,0.027009,0.347939,0.231069,0.258518,0.025217,0.112548,0.006171,0.121151,-0.049886,...,0.152486,-0.058425,0.100467,0.114749,-0.332034,-0.151083,0.270189,-0.073737,0.109743,YPVFAQQNYANPREANGRIVCANCHLAQKAVEIEVPQAVLPDTVFE...
4191,-0.168196,-0.129169,0.149304,0.163379,0.359575,-0.138917,0.055724,-0.027600,0.038103,-0.078590,...,-0.055973,0.085158,0.092871,0.082625,-0.091545,-0.031308,0.192485,0.128901,0.101561,YQPNYFLSIPITNKKITAGIKVLQNSILRQDNRLTKAMVGDGSFHI...
4192,0.005642,-0.068382,0.233585,0.050688,0.302404,0.106692,-0.101524,-0.011044,0.014735,-0.033642,...,-0.004114,0.079132,0.042417,-0.018084,-0.224415,-0.123799,0.261922,0.064153,-0.069107,YTGFTPERYNKIQFGMDRTLVWQLAGADQSCSDQVERIICYNNPDH...

In [8]:
X_used = normalize(df_encoders.drop(columns=["sequence"]).values, norm="l2")
X_used

array([[-0.00314729, -0.04156449,  0.07609016, ...,  0.03740707,
         0.01846079, -0.0179027 ],
       [ 0.00684718, -0.05288608,  0.06960224, ...,  0.04209224,
         0.03862475, -0.03666819],
       [-0.01762744, -0.01853952,  0.02596525, ...,  0.04604495,
         0.00717818, -0.01161284],
       ...,
       [-0.0066471 ,  0.00498292,  0.06419185, ...,  0.04984758,
        -0.01360393,  0.02024665],
       [-0.03309161, -0.02541327,  0.02937475, ...,  0.03787045,
         0.02536066,  0.01998157],
       [ 0.00102954, -0.01247726,  0.04262082, ...,  0.04779125,
         0.01170556, -0.01260944]], shape=(4193, 320), dtype=float32)